### ISSUE TITLE
请问一下，加载dll失败错误126，这个还需要其他的动态库吗？

### ISSUE THREAD

**Issue by Whaooo** [SP0N9E/OPPluginForUnreal#2]
你好，错误如下：
LogTemp: Error: E:/UEProject/OPTest/Plugins/LoadDll/ThirdParty/OpenPose/lib/caffehdf5.dll not loaded
LogWindows: Failed to load 'E:/UEProject/OPTest/Plugins/LoadDll/ThirdParty/OpenPose/lib/caffehdf5_hl.dll' (GetLastError=126)
LogTemp: Error: E:/UEProject/OPTest/Plugins/LoadDll/ThirdParty/OpenPose/lib/caffehdf5_hl.dll not loaded
LogTemp: Warning: E:/UEProject/OPTest/Plugins/LoadDll/ThirdParty/OpenPose/lib/caffezlib1.dll loaded
LogTemp: Warning: E:/UEProject/OPTest/Plugins/LoadDll/ThirdParty/OpenPose/lib/cublas64_100.dll loaded
LogTemp: Warning: E:/UEProject/OPTest/Plugins/LoadDll/ThirdParty/OpenPose/lib/cudart64_100.dll loaded
LogTemp: Warning: E:/UEProject/OPTest/Plugins/LoadDll/ThirdParty/OpenPose/lib/curand64_100.dll loaded
LogTemp: Warning: E:/UEProject/OPTest/Plugins/LoadDll/ThirdParty/OpenPose/lib/cudnn64_7.dll loaded
LogTemp: Warning: E:/UEProject/OPTest/Plugins/LoadDll/ThirdParty/OpenPose/lib/freeglut.dll loaded
LogTemp: Warning: E:/UEProject/OPTest/Plugins/LoadDll/ThirdParty/OpenPose/lib/gflags.dll loaded
LogTemp: Warning: E:/UEProject/OPTest/Plugins/LoadDll/ThirdParty/OpenPose/lib/glog.dll loaded
LogTemp: Warning: E:/UEProject/OPTest/Plugins/LoadDll/ThirdParty/OpenPose/lib/libgcc_s_seh-1.dll loaded
LogWindows: Failed to load 'E:/UEProject/OPTest/Plugins/LoadDll/ThirdParty/OpenPose/lib/libgfortran-3.dll' (GetLastError=126)
LogTemp: Error: E:/UEProject/OPTest/Plugins/LoadDll/ThirdParty/OpenPose/lib/libgfortran-3.dll not loaded
LogWindows: Failed to load 'E:/UEProject/OPTest/Plugins/LoadDll/ThirdParty/OpenPose/lib/libopenblas.dll' (GetLastError=126)
LogTemp: Error: E:/UEProject/OPTest/Plugins/LoadDll/ThirdParty/OpenPose/lib/libopenblas.dll not loaded
LogWindows: Failed to load 'E:/UEProject/OPTest/Plugins/LoadDll/ThirdParty/OpenPose/lib/caffe.dll' (GetLastError=126)
LogTemp: Error: E:/UEProject/OPTest/Plugins/LoadDll/ThirdParty/OpenPose/lib/caffe.dll not loaded

目前机器cuda版本是11.0，cudnn是V8.2.4，请问是还需要链接其他的动态库吗？
谢谢。

**Comment by SP0N9E** [comment]
按道理是不需要的 只需将文件夹models和ThirdParty按照要求放入指定文件夹即可满足所需动态库要求
如果还是Failed to load， 可以尝试将caffe.dll等动态链接库直接放在UE编译出的项目可执行文件所在的目录，即直接放置在exe的根目录
